import{a as f,S as d,i}from"./assets/vendor-1AYLTIiv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m="50674285-d69cfe0c44a4bfde391ce2dd2",y="https://pixabay.com/api/";function g(a){const r={key:m,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0};return f.get(y,{params:r}).then(s=>{if(s.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return s.data})}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),h=new d(".gallery a",{captionsData:"alt",captionPosition:"top-right",captionDelay:250});function L(a){const r=a.map(({largeImageURL:s,webformatURL:o,tags:e,likes:t,views:n,comments:p,downloads:u})=>`<li class="gallery-item"> <a href="${s}">
                <img src="${o}" alt="${e}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${t}</span></p>
                <p class="text">Views <span class="span">${n}</span></p>
                <p class="text">Comments <span class="span">${p}</span></p>
                <p class="text">Downloads <span class="span">${u}</span></p>
            </div></li>`).join("");c.insertAdjacentHTML("beforeend",r),h.refresh()}function w(){c.innerHTML=""}function x(){l.style.display="flex"}function b(){l.style.display="none"}const P=document.querySelector("form");P.addEventListener("submit",a=>{a.preventDefault();const r=a.target.elements["search-text"].value.trim();if(!r){i.warning({title:"warning",message:"Please enter a search term",position:"topRight"});return}w(),x(),g(r).then(s=>{const{hits:o}=s;o.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):L(o)}).catch(s=>{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{b()})});
//# sourceMappingURL=index.js.map
