import{a as b,S,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const q="50674285-d69cfe0c44a4bfde391ce2dd2",x="https://pixabay.com/api/";async function y(o,t,a){const s={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a};try{return(await b.get(x,{params:s})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const g=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-btn"),v=new S(".gallery a",{captionsData:"alt",captionPosition:"top-right",captionDelay:250});function h(o){const t=o.map(({largeImageURL:a,webformatURL:s,tags:e,likes:r,views:i,comments:L,downloads:P})=>`<li class="gallery-item"> <a href="${a}">
                <img src="${s}" alt="${e}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${r}</span></p>
                <p class="text">Views <span class="span">${i}</span></p>
                <p class="text">Comments <span class="span">${L}</span></p>
                <p class="text">Downloads <span class="span">${P}</span></p>
            </div></li>`).join("");g.insertAdjacentHTML("beforeend",t),v.refresh()}function $(){g.innerHTML=""}function w(){f.style.display="flex"}function p(){f.style.display="none"}function B(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const M=document.querySelector("form"),E=document.querySelector(".load-btn");let n=1,u=15,d="";p();M.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(!t){c.warning({title:"warning",message:"Please enter a search term",position:"topRight"});return}n=1,d=t,$(),w(),l();try{const a=await y(d,n,u),{hits:s}=a;s.length===0?(c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l()):(h(s),B());const e=Math.ceil(a.totalHits/u);n>=e&&l()}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}});E.addEventListener("click",async()=>{n+=1,w();try{const o=await y(d,n,u);h(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}const a=Math.ceil(o.totalHits/u);n>=a&&(l(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}});
//# sourceMappingURL=index.js.map
